type User @collection(name: "users") {
  email: String! @unique(index: "user_by_email")
}

enum Unit {
  GRAM
  COUNT
}

type Ingredient @embedded {
  food: Food! @related
  amount: Float!
  unit: Unit!
}

type Recipe @collection(name: "recipes") {
  name: String!
  ingredients: [Ingredient!]
}

type Food @collection(name: "foods") {
  name: String! @unique(index: "food_by_name")
}
type Query {
  allRecipes: [Recipe!] @index(name: "allRecipes")
}

input CreateIngredientInput {
  name: String!
  amount: Float!
  unit:Unit!
}

input CreateRecipeInput {
  title: String!
  ingredients: [CreateIngredientInput!]
}
