type User @collection(name: "users") {
  email: String! @unique(index: "user_by_email")
}

type List @collection(name: "lists") {
  title: String!
  todos: [Todo] @relation
  owner: User! @relation
}
type Todo @collection(name: "todos") {
  title: String!
  completed: Boolean!
  list: List
  owner: User! @relation
}

type Query {
  allLists: [List] @index(name: "all_lists")
  ownedLists: [List] @resolver(name: "getOwnedLists", paginated: false)
}
